### ISSUE TITLE
Need to add sprite parts into one batch node.

### ISSUE THREAD

**Issue by crookedbard** [jeremyjh/Spriter2dX#3]
Now my sprite animation consists of 10 sprites - hands, torso, head and other.
I followed your example and it added 10 GL calls to the scene. It would be great if all the sprite parts would be added to sprite frame cache so it would be just 1 GL call.

**Comment by jeremyjh** [comment]
Hi, you need to add them to the Cocos2dX frame cache yourself, then you can tell the animation node to use the cacheLoader. 

```c++
Spriter2dX::AnimationNode::create(scml, Spriter2dX::AnimationNode::cacheLoader());
```

**Comment by crookedbard** [comment]
Thanks for the fast response!
