### ISSUE TITLE
Is it possible to enable and disable instance animation playback?

### ISSUE THREAD

**Issue by crookedbard** [jeremyjh/Spriter2dX#4]
I have Spriter animation file that contains 2 types of animations: one type is continues animation (walk, run) other type - played once (attack, being hit).

So I create an animation node and 1 entityInstnace with "play" function.
On animations walk & run everything works great. Animation loops continuously.
But now with other animations I try to catch animation end time to stop it precisely when the animation is finished. 

```
auto scml = cocos2d::FileUtils::getInstance()->fullPathForFilename("char/plr1/Animations.scml");
    _plrAnimationNode = Spriter2dX::AnimationNode::create(scml, Spriter2dX::AnimationNode::cacheLoader());
    _plrEntityInstance = _plrAnimationNode->play("Player sprite");
    _plrEntityInstance->setCurrentAnimation("Front - Idle");
//    _plrEntityInstance->animationJustFinished(); // it never finishes because animation always loops
//    _plrEntityInstance->animationJustLooped(); // it does not hit precicely on animation end, but when new animation begins
    _plrEntityInstance->pausePlayback(); //animation stops instantely
```

How to get a callback when animation is finished?

**Comment by jeremyjh** [comment]
SpriterPlusPlus is controlling the animation so you need to refer to that API. I don't see a callback but there is a method `animationJustFinished` on the EntityInstance. Sorry I can't be of more help but I've not really used this in like three years :)

**Comment by crookedbard** [comment]
Hi, I have modified your AnimationNode class to allow some methods to be overriden: added virtual to update, play, playonce. Removed the impl. Now when I overriden your update method I have better control of the animation and its completion :)
